Repository stolostron/build-harness-extensions, pull requests merged in 2021-02, with the labels that each got.

#114 sonar: add targets for openshiftci sonar scans
  modules/sonar/Makefile
Labels: approved, dco-signoff: no

#115 sonar: add logging to osci sonar targets
  modules/sonar/Makefile
Labels: approved

#116 sonar: add logging to osci sonar targets
  modules/sonar/Makefile
Labels: approved

#118 sonar: add logging to osci sonar targets
  modules/sonar/Makefile
Labels: approved

#119 sonar: add logging to osci sonar targets
  modules/sonar/Makefile
Labels: approved

#120 sonar: add properties to sonar-scanner for osci
  modules/sonar/Makefile
Labels: approved

#122 osci: fix jq reference
  modules/osci/Makefile
Labels: approved, lgtm

#123 clusterpool: add CLUSTERPOOL_HOST_KUBE_SECRET
  modules/clusterpool/Makefile
Labels: approved, lgtm

#124 Create update-image-builder.yml
  .github/workflows/update-image-builder.yml
Labels: approved, lgtm

#125 sonar: ignore non-zero exit code from go test and gosec [skip ci]
  modules/sonar/Makefile
Labels: approved, lgtm

#127 action: update update-image-builder [skip ci]
  .github/workflows/update-image-builder.yml
Labels: approved, lgtm

#128 sonar: change artifact directory env var name
  modules/sonar/Makefile
Labels: approved, lgtm

#129 Support GITHUB_USER and GITHUB_TOKEN Travis vars
  modules/release-ff/bin/release_ff.sh
Labels: approved, lgtm

#130 sonar: undo rename of artifact env var in the presubmit target
  modules/sonar/Makefile
Labels: approved, lgtm

#131 Make some noise when the push to quay fails
  modules/pipeline-manifest/Makefile
Labels: approved, lgtm
